# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BuildMe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BuildMe
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Fabric', '~> 1.8.2'
  pod 'Crashlytics', '~> 3.11.1'

  target 'BuildMeTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'BuildMeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

	

end
